// Code generated by yaggo. DO NOT EDIT.

package petstore

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// DefaultMaxResponseBytes is the response-body cap applied when no
// WithMaxResponseBytes option is supplied. 8 MiB accommodates typical JSON
// payloads while preventing a misbehaving (or hostile) upstream from
// exhausting the client's memory with a gigabyte-scale response. Override
// with WithMaxResponseBytes(0) to disable or any positive value to resize.
const DefaultMaxResponseBytes int64 = 8 << 20

// RequestEditor is invoked after the HTTP request is built but before it is
// dispatched. Use it to inject auth headers, tracing, etc. Returning an error
// aborts the request and propagates the error to the caller.
type RequestEditor func(ctx context.Context, req *http.Request) error

// Client is the generated HTTP client for this API.
type Client struct {
	baseURL          string
	httpClient       *http.Client
	headers          map[string]string
	requestEditors   []RequestEditor
	maxResponseBytes int64
}

// ClientOption configures NewClient.
type ClientOption func(*Client)

// WithHTTPClient swaps the underlying HTTP transport (e.g. to set timeouts or
// install a custom RoundTripper).
func WithHTTPClient(hc *http.Client) ClientOption {
	return func(c *Client) { c.httpClient = hc }
}

// WithHeader installs a default header sent on every request. Later calls
// overwrite earlier ones for the same key.
func WithHeader(key, value string) ClientOption {
	return func(c *Client) { c.headers[key] = value }
}

// WithUserAgent is a convenience wrapper for WithHeader("User-Agent", ua).
func WithUserAgent(ua string) ClientOption {
	return WithHeader("User-Agent", ua)
}

// WithRequestEditor appends a per-request mutator. Editors run in registration
// order; the first one to return an error short-circuits the call.
func WithRequestEditor(fn RequestEditor) ClientOption {
	return func(c *Client) { c.requestEditors = append(c.requestEditors, fn) }
}

// WithMaxResponseBytes caps the number of bytes the client will read from any
// response body. Defense-in-depth against an upstream returning gigabytes of
// JSON; pair with http.Client.Timeout for the orthogonal "slow byte stream"
// defence. A value of 0 disables the cap entirely. The default is
// DefaultMaxResponseBytes.
func WithMaxResponseBytes(n int64) ClientOption {
	return func(c *Client) { c.maxResponseBytes = n }
}

// NewClient creates a Client targeting baseURL, applying any options.
// baseURL must be a valid http or https URL with a non-empty host. The
// trailing slash on the path (if any) is stripped so request paths never
// produce a double slash. A query string or fragment on baseURL is
// rejected: concatenating raw with operation paths corrupts the URL
// (the `?` gets pulled into the next segment), and there's no canonical
// way to merge them with per-call query parameters — pass defaults via
// WithRequestEditor instead.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL %q: %w", baseURL, err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return nil, fmt.Errorf("base URL scheme must be http or https, got %q", u.Scheme)
	}
	if u.Host == "" {
		return nil, fmt.Errorf("base URL must include a host")
	}
	if u.RawQuery != "" || u.Fragment != "" {
		return nil, fmt.Errorf("base URL must not contain a query string or fragment; use WithRequestEditor to attach default query params")
	}
	c := &Client{
		baseURL:          strings.TrimRight(baseURL, "/"),
		httpClient:       &http.Client{CheckRedirect: safeRedirectPolicy},
		headers:          make(map[string]string),
		maxResponseBytes: DefaultMaxResponseBytes,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// ListPets List all pets
func (c *Client) ListPets(ctx context.Context, limit *int32, status *PetStatus) ([]Pet, error) {
	// Locals use the "qry" / "hdrs" / "reqPath" / "httpResp" prefixes (not
	// the shorter q/h/path/resp) so spec query parameters named q, h, path
	// or resp don't shadow them.
	reqPath := "/pets"
	qry := url.Values{}
	if limit != nil {
		qry.Set("limit", strconv.FormatInt(int64(*limit), 10))
	}
	if status != nil {
		qry.Set("status", string(*status))
	}
	var hdrs http.Header
	httpResp, err := c.do(ctx, "GET", reqPath, nil, "", "application/json", hdrs, qry)
	if err != nil {
		var zero []Pet
		return zero, err
	}
	return decodeResponse[[]Pet](httpResp, c.maxResponseBytes)
}

// CreatePet Create a pet
func (c *Client) CreatePet(ctx context.Context, body NewPet) (Pet, error) {
	// Locals use the "qry" / "hdrs" / "reqPath" / "httpResp" prefixes (not
	// the shorter q/h/path/resp) so spec query parameters named q, h, path
	// or resp don't shadow them.
	reqPath := "/pets"
	qry := url.Values(nil)
	var hdrs http.Header
	httpResp, err := c.do(ctx, "POST", reqPath, body, "application/json", "application/json", hdrs, qry)
	if err != nil {
		var zero Pet
		return zero, err
	}
	return decodeResponse[Pet](httpResp, c.maxResponseBytes)
}

// GetPet Get a pet by ID
func (c *Client) GetPet(ctx context.Context, petId int64) (Pet, error) {
	// Locals use the "qry" / "hdrs" / "reqPath" / "httpResp" prefixes (not
	// the shorter q/h/path/resp) so spec query parameters named q, h, path
	// or resp don't shadow them.
	reqPath := fmt.Sprintf("/pets/%d", petId)
	qry := url.Values(nil)
	var hdrs http.Header
	httpResp, err := c.do(ctx, "GET", reqPath, nil, "", "application/json", hdrs, qry)
	if err != nil {
		var zero Pet
		return zero, err
	}
	return decodeResponse[Pet](httpResp, c.maxResponseBytes)
}

// UpdatePet Update a pet
func (c *Client) UpdatePet(ctx context.Context, petId int64, body NewPet) (Pet, error) {
	// Locals use the "qry" / "hdrs" / "reqPath" / "httpResp" prefixes (not
	// the shorter q/h/path/resp) so spec query parameters named q, h, path
	// or resp don't shadow them.
	reqPath := fmt.Sprintf("/pets/%d", petId)
	qry := url.Values(nil)
	var hdrs http.Header
	httpResp, err := c.do(ctx, "PUT", reqPath, body, "application/json", "application/json", hdrs, qry)
	if err != nil {
		var zero Pet
		return zero, err
	}
	return decodeResponse[Pet](httpResp, c.maxResponseBytes)
}

// DeletePet Delete a pet
func (c *Client) DeletePet(ctx context.Context, petId int64) error {
	// Locals use the "qry" / "hdrs" / "reqPath" / "httpResp" prefixes (not
	// the shorter q/h/path/resp) so spec query parameters named q, h, path
	// or resp don't shadow them.
	reqPath := fmt.Sprintf("/pets/%d", petId)
	qry := url.Values(nil)
	var hdrs http.Header
	httpResp, err := c.do(ctx, "DELETE", reqPath, nil, "", "application/json", hdrs, qry)
	if err != nil {
		return err
	}
	drainAndClose(httpResp.Body)
	if httpResp.StatusCode >= 400 {
		return fmt.Errorf("http error: %d", httpResp.StatusCode)
	}
	return nil
}

func (c *Client) do(ctx context.Context, method, path string, body any, contentType, accept string, extraHeaders http.Header, query url.Values) (*http.Response, error) {
	// Per-request buffer allocation rather than a sync.Pool of *bytes.Buffer:
	// http.NewRequestWithContext for *bytes.Buffer captures v.Bytes() (a slice
	// into the buffer's backing array) for req.GetBody (used on redirect
	// retries). Pooling that buffer back risks a different goroutine
	// overwriting the array while a custom transport still holds the request
	// for replay. The allocation is cheap, the race isn't.
	var reqBody io.Reader
	if body != nil {
		var buf bytes.Buffer
		if err := json.NewEncoder(&buf).Encode(body); err != nil {
			return nil, fmt.Errorf("marshalling request body: %w", err)
		}
		reqBody = &buf
	}
	u := c.baseURL + path
	if len(query) > 0 {
		u += "?" + query.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u, reqBody)
	if err != nil {
		return nil, err
	}
	if body != nil && contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	if accept != "" {
		req.Header.Set("Accept", accept)
	}
	for k, v := range c.headers {
		req.Header.Set(k, v)
	}
	// Operation-defined headers (per-call) override client defaults but yield
	// to RequestEditors, which run after this loop.
	for k, vs := range extraHeaders {
		for _, v := range vs {
			req.Header.Set(k, v)
		}
	}
	for _, ed := range c.requestEditors {
		if err := ed(ctx, req); err != nil {
			return nil, err
		}
	}
	resp, err := c.httpClient.Do(req)
	if err != nil {
		// Some failure modes (CheckRedirect rejection, transport retries)
		// return a non-nil resp alongside the error. Drain and close so the
		// connection can return to the pool, and return nil resp so callers
		// can't accidentally dereference a half-formed response.
		if resp != nil && resp.Body != nil {
			drainAndClose(resp.Body)
		}
		return nil, err
	}
	return resp, nil
}

// drainAndClose discards up to drainLimit bytes from body, then closes it.
// HTTP/1.1 keep-alive requires the response body to be fully consumed AND
// closed for the underlying TCP connection to return to the pool — but
// unbounded io.Copy means an upstream sending gigabytes of data forces the
// client to download all of it (defeating the WithMaxResponseBytes memory
// cap on the time/bandwidth axes). drainLimit covers typical trailing
// JSON whitespace; if there's more, Close() releases the connection (no
// reuse, but bounded read).
const drainLimit = 64 << 10

func drainAndClose(body io.ReadCloser) {
	_, _ = io.CopyN(io.Discard, body, drainLimit)
	_ = body.Close()
}

// safeRedirectPolicy is the CheckRedirect function installed on the default
// http.Client created by NewClient. It strips the Authorization header when
// the redirect target degrades from HTTPS to HTTP so that bearer tokens and
// Basic credentials are not sent in cleartext.
//
// Go's net/http copies Authorization across same-host redirects without
// checking for a scheme downgrade (it only checks the host, not the scheme).
// This policy closes that gap. Callers who inject their own *http.Client via
// WithHTTPClient are responsible for their own redirect policy.
func safeRedirectPolicy(req *http.Request, via []*http.Request) error {
	if len(via) > 0 && via[0].URL.Scheme == "https" && req.URL.Scheme != "https" {
		req.Header.Del("Authorization")
	}
	return nil
}

func decodeResponse[T any](resp *http.Response, maxBytes int64) (T, error) {
	var zero T
	defer drainAndClose(resp.Body)
	// Cap the bytes we'll read from the body before handing it to the JSON
	// decoder. The defer above still drains whatever remains so that HTTP/1.1
	// keep-alive can recycle the connection.
	body := resp.Body
	var bodyReader io.Reader = body
	if maxBytes > 0 {
		bodyReader = io.LimitReader(body, maxBytes)
	}
	if resp.StatusCode >= 400 {
		var apiErr map[string]string
		if err := json.NewDecoder(bodyReader).Decode(&apiErr); err == nil {
			if msg, ok := apiErr["error"]; ok {
				return zero, fmt.Errorf("api error %d: %s", resp.StatusCode, msg)
			}
		}
		return zero, fmt.Errorf("http error: %d", resp.StatusCode)
	}
	if err := json.NewDecoder(bodyReader).Decode(&zero); err != nil {
		return zero, fmt.Errorf("decoding response: %w", err)
	}
	return zero, nil
}
