// Code generated by yaggo. DO NOT EDIT.

package petstore

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/go-chi/chi/v5"
)

// DefaultMaxBodyBytes is the request-body size cap applied when no
// WithMaxBodyBytes option is supplied. 1 MiB is enough for typical JSON
// payloads while preventing a single client from holding gigabytes of memory.
// Override with WithMaxBodyBytes(0) for unlimited (not recommended on public
// networks) or any positive value to raise/lower the cap.
const DefaultMaxBodyBytes int64 = 1 << 20

// Middleware wraps an HTTP handler. Compatible with any chi/v5 middleware
// (any func(http.Handler) http.Handler).
type Middleware = func(http.Handler) http.Handler

// ErrorHandler renders error responses produced by the generated handlers
// (bad path params, undecodable bodies, failed Validate(), etc.). The default
// writes {"error": http.StatusText(status)} as JSON with the given status
// code — the wrapped err is NOT echoed to the client, so internal details
// (decoder messages, the bytes the client sent) don't leak. The full err is
// still passed to this callback, so a custom handler can log it or surface
// more detail when its threat model permits.
type ErrorHandler func(w http.ResponseWriter, r *http.Request, err error, status int)

// ServerOption configures RegisterHandlers.
type ServerOption func(*serverConfig)

type serverConfig struct {
	middlewares  []Middleware
	errorHandler ErrorHandler
	maxBodyBytes int64
}

// WithMiddleware appends an HTTP middleware applied to every generated handler.
// Middlewares run in the order they were registered (outermost first).
func WithMiddleware(mw Middleware) ServerOption {
	return func(c *serverConfig) { c.middlewares = append(c.middlewares, mw) }
}

// WithErrorHandler overrides the default JSON error renderer.
func WithErrorHandler(h ErrorHandler) ServerOption {
	return func(c *serverConfig) { c.errorHandler = h }
}

// WithMaxBodyBytes caps the size of the JSON request body each handler will
// read. Bodies that exceed n bytes are rejected with HTTP 413 before the spec
// type is decoded. A value of 0 disables the cap entirely (not recommended on
// public networks). The default is DefaultMaxBodyBytes.
func WithMaxBodyBytes(n int64) ServerOption {
	return func(c *serverConfig) { c.maxBodyBytes = n }
}

// defaultErrorHandler responds with a status-keyed generic message
// ("Bad Request", "Request Entity Too Large", …) and never echoes the wrapped
// err to the client. This keeps internal details (JSON decoder fields,
// strconv parse errors quoting user-sent values) out of HTTP responses by
// default. Custom handlers installed via WithErrorHandler still receive the
// full err and may emit whatever detail their threat model permits.
func defaultErrorHandler(w http.ResponseWriter, _ *http.Request, _ error, status int) {
	WriteJSON(w, status, map[string]string{"error": http.StatusText(status)})
}

func chainMiddleware(mws []Middleware) func(http.Handler) http.Handler {
	return func(h http.Handler) http.Handler {
		for i := len(mws) - 1; i >= 0; i-- {
			h = mws[i](h)
		}
		return h
	}
}

// ListPetsParams holds query parameters for GET /pets.
type ListPetsParams struct {
	Limit  *int32     `query:"limit"`
	Status *PetStatus `query:"status"`
}

// ServerInterface must be implemented to serve the API.
type ServerInterface interface {
	// ListPets List all pets
	ListPets(w http.ResponseWriter, r *http.Request, params ListPetsParams)
	// CreatePet Create a pet
	CreatePet(w http.ResponseWriter, r *http.Request, body NewPet)
	// GetPet Get a pet by ID
	GetPet(w http.ResponseWriter, r *http.Request, petId int64)
	// UpdatePet Update a pet
	UpdatePet(w http.ResponseWriter, r *http.Request, petId int64, body NewPet)
	// DeletePet Delete a pet
	DeletePet(w http.ResponseWriter, r *http.Request, petId int64)
}

// RegisterHandlers mounts all routes onto r, applying any provided options.
func RegisterHandlers(r chi.Router, si ServerInterface, opts ...ServerOption) {
	cfg := &serverConfig{
		errorHandler: defaultErrorHandler,
		maxBodyBytes: DefaultMaxBodyBytes,
	}
	for _, opt := range opts {
		opt(cfg)
	}
	wrap := chainMiddleware(cfg.middlewares)
	r.Method("GET", "/pets", wrap(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Parse the URL query once and reuse for every parameter; calling
		// r.URL.Query() per parameter would re-tokenise RawQuery N times.
		query := r.URL.Query()
		var params ListPetsParams
		{
			v := query.Get("limit")
			if v != "" {
				n, err := strconv.ParseInt(v, 10, 32)
				if err == nil {
					tmp := int32(n)
					params.Limit = &tmp
				}
			}
		}
		{
			v := query.Get("status")
			if v != "" {
				tmp := PetStatus(v)
				params.Status = &tmp
			}
		}
		si.ListPets(w, r, params)
	})))
	r.Method("POST", "/pets", wrap(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _, err := decodeCreatePetBody(w, r, cfg)
		if err != nil {
			return
		}
		if err := body.Validate(); err != nil {
			cfg.errorHandler(w, r, err, http.StatusBadRequest)
			return
		}
		si.CreatePet(w, r, body)
	})))
	r.Method("GET", "/pets/{petId}", wrap(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		petIdRaw := chi.URLParam(r, "petId")
		petIdParsed, err := strconv.ParseInt(petIdRaw, 10, 64)
		if err != nil {
			cfg.errorHandler(w, r, fmt.Errorf("invalid path param 'petId': %w", err), http.StatusBadRequest)
			return
		}
		petId := int64(petIdParsed)
		si.GetPet(w, r, petId)
	})))
	r.Method("PUT", "/pets/{petId}", wrap(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		petIdRaw := chi.URLParam(r, "petId")
		petIdParsed, err := strconv.ParseInt(petIdRaw, 10, 64)
		if err != nil {
			cfg.errorHandler(w, r, fmt.Errorf("invalid path param 'petId': %w", err), http.StatusBadRequest)
			return
		}
		petId := int64(petIdParsed)
		body, _, err := decodeUpdatePetBody(w, r, cfg)
		if err != nil {
			return
		}
		if err := body.Validate(); err != nil {
			cfg.errorHandler(w, r, err, http.StatusBadRequest)
			return
		}
		si.UpdatePet(w, r, petId, body)
	})))
	r.Method("DELETE", "/pets/{petId}", wrap(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		petIdRaw := chi.URLParam(r, "petId")
		petIdParsed, err := strconv.ParseInt(petIdRaw, 10, 64)
		if err != nil {
			cfg.errorHandler(w, r, fmt.Errorf("invalid path param 'petId': %w", err), http.StatusBadRequest)
			return
		}
		petId := int64(petIdParsed)
		si.DeletePet(w, r, petId)
	})))
}

// decodeCreatePetBody reads and JSON-decodes the request body for POST /pets.
// It enforces cfg.maxBodyBytes via http.MaxBytesReader and routes size-overflow
// errors to HTTP 413 (Request Entity Too Large) and decode failures to HTTP 400.
// A Content-Type mismatch against the spec-declared media type returns
// HTTP 415 (Unsupported Media Type). The bool return is true when a body was
// actually decoded (always true for required bodies; false for an absent optional
// body). On error the response has already been written; callers must just return.
func decodeCreatePetBody(w http.ResponseWriter, r *http.Request, cfg *serverConfig) (NewPet, bool, error) {
	var out NewPet
	// Content-Type validation: spec declares application/json for
	// this operation. Reject other media types up front so clients see 415
	// instead of a confusing JSON parse error. An absent header is tolerated
	// — many small clients omit it and the decoder will catch malformed
	// bodies anyway. mime parameters (";charset=…") are stripped before
	// comparison.
	if ct := r.Header.Get("Content-Type"); ct != "" {
		base := ct
		if i := strings.IndexByte(base, ';'); i >= 0 {
			base = base[:i]
		}
		base = strings.TrimSpace(base)
		if !strings.EqualFold(base, "application/json") {
			cfg.errorHandler(w, r, fmt.Errorf("unsupported Content-Type %q, expected %s", ct, "application/json"), http.StatusUnsupportedMediaType)
			return out, false, fmt.Errorf("unsupported content-type")
		}
	}
	body := r.Body
	if cfg.maxBodyBytes > 0 {
		body = http.MaxBytesReader(w, r.Body, cfg.maxBodyBytes)
	}
	dec := json.NewDecoder(body)
	if err := dec.Decode(&out); err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			cfg.errorHandler(w, r, fmt.Errorf("request body exceeds %d bytes", maxErr.Limit), http.StatusRequestEntityTooLarge)
			return out, false, err
		}
		cfg.errorHandler(w, r, fmt.Errorf("invalid request body: %w", err), http.StatusBadRequest)
		return out, false, err
	}
	return out, true, nil
}

// decodeUpdatePetBody reads and JSON-decodes the request body for PUT /pets/{petId}.
// It enforces cfg.maxBodyBytes via http.MaxBytesReader and routes size-overflow
// errors to HTTP 413 (Request Entity Too Large) and decode failures to HTTP 400.
// A Content-Type mismatch against the spec-declared media type returns
// HTTP 415 (Unsupported Media Type). The bool return is true when a body was
// actually decoded (always true for required bodies; false for an absent optional
// body). On error the response has already been written; callers must just return.
func decodeUpdatePetBody(w http.ResponseWriter, r *http.Request, cfg *serverConfig) (NewPet, bool, error) {
	var out NewPet
	// Content-Type validation: spec declares application/json for
	// this operation. Reject other media types up front so clients see 415
	// instead of a confusing JSON parse error. An absent header is tolerated
	// — many small clients omit it and the decoder will catch malformed
	// bodies anyway. mime parameters (";charset=…") are stripped before
	// comparison.
	if ct := r.Header.Get("Content-Type"); ct != "" {
		base := ct
		if i := strings.IndexByte(base, ';'); i >= 0 {
			base = base[:i]
		}
		base = strings.TrimSpace(base)
		if !strings.EqualFold(base, "application/json") {
			cfg.errorHandler(w, r, fmt.Errorf("unsupported Content-Type %q, expected %s", ct, "application/json"), http.StatusUnsupportedMediaType)
			return out, false, fmt.Errorf("unsupported content-type")
		}
	}
	body := r.Body
	if cfg.maxBodyBytes > 0 {
		body = http.MaxBytesReader(w, r.Body, cfg.maxBodyBytes)
	}
	dec := json.NewDecoder(body)
	if err := dec.Decode(&out); err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			cfg.errorHandler(w, r, fmt.Errorf("request body exceeds %d bytes", maxErr.Limit), http.StatusRequestEntityTooLarge)
			return out, false, err
		}
		cfg.errorHandler(w, r, fmt.Errorf("invalid request body: %w", err), http.StatusBadRequest)
		return out, false, err
	}
	return out, true, nil
}

// WriteContent encodes v as JSON and writes it with the given Content-Type
// and status. Use it when the OpenAPI response media type is a JSON variant
// other than "application/json" (e.g. "application/vnd.api+json",
// "application/hal+json", "application/problem+json").
//
// The response is encoded into a buffer before any header is written so that
// a marshal failure can still be reported via http.Error with the correct
// 500 status — writing directly to w would commit the success status before
// the failure could be detected.
func WriteContent(w http.ResponseWriter, status int, contentType string, v any) {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(v); err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", contentType)
	w.WriteHeader(status)
	_, _ = w.Write(buf.Bytes())
}

// WriteJSON is the common case of WriteContent with Content-Type
// "application/json".
func WriteJSON(w http.ResponseWriter, status int, v any) {
	WriteContent(w, status, "application/json", v)
}

// WriteError writes a JSON error response. Convenience helper for custom
// handler implementations; generated routes go through the configured
// ErrorHandler instead.
func WriteError(w http.ResponseWriter, status int, msg string) {
	WriteJSON(w, status, map[string]string{"error": msg})
}
