// Code generated by yaggo. DO NOT EDIT.

package petstore

import "fmt"

type NewPet struct {
	// Name of the pet
	Name   string     `json:"name"`
	Status *PetStatus `json:"status,omitempty"`
	// Optional tag
	Tag *string `json:"tag,omitempty"`
}

func (v NewPet) Validate() error {
	if v.Name == "" {
		return fmt.Errorf("field 'name' is required")
	}
	if v.Status != nil {
		if err := v.Status.Validate(); err != nil {
			return fmt.Errorf("field 'status': %w", err)
		}
	}
	return nil
}

type Pet struct {
	// Unique pet ID
	Id int64 `json:"id"`
	// Name of the pet
	Name   string     `json:"name"`
	Status *PetStatus `json:"status,omitempty"`
	// Optional tag
	Tag *string `json:"tag,omitempty"`
}

func (v Pet) Validate() error {
	if v.Name == "" {
		return fmt.Errorf("field 'name' is required")
	}
	if v.Status != nil {
		if err := v.Status.Validate(); err != nil {
			return fmt.Errorf("field 'status': %w", err)
		}
	}
	return nil
}

type PetStatus string

const (
	PetStatusAvailable PetStatus = "available"
	PetStatusPending   PetStatus = "pending"
	PetStatusSold      PetStatus = "sold"
)

func (v PetStatus) Validate() error {
	switch v {
	case PetStatusAvailable, PetStatusPending, PetStatusSold:
		return nil
	}
	return fmt.Errorf("invalid PetStatus value: %q", string(v))
}
